apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipe
  template:
    metadata:
      labels:
        app: recipe
    spec:
      containers:
      - name: recipe-app
        image: your_dockerhub_username/recipe-app:latest
        ports:
        - containerPort: 5000
